-- 코드를 입력하세요
SELECT I.ANIMAL_ID ANIMAL_ID, ANIMAL_TYPE, NAME NAME
FROM
    (SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_INTAKE
    FROM ANIMAL_INS) I
    JOIN
    (SELECT ANIMAL_ID, SEX_UPON_OUTCOME
    FROM ANIMAL_OUTS) O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (SEX_UPON_INTAKE LIKE "%Intact%"
    AND SEX_UPON_OUTCOME NOT LIKE "%Intact%")

ORDER BY I.ANIMAL_ID
;