-- 코드를 입력하세요
SELECT NAME NAME, DATETIME DATETIME
FROM
    (SELECT ANIMAL_ID, NAME, DATETIME
    FROM ANIMAL_INS) I
    LEFT JOIN
    (SELECT ANIMAL_ID
    FROM ANIMAL_OUTS) O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME
LIMIT 3
;