# -- 코드를 입력하세요
# SELECT J.FLAVOR, SUM(J.TOTAL_ORDER)
# FROM FIRST_HALF F
# JOIN JULY J ON (F.SHIPMENT_ID=J.SHIPMENT_ID AND F.FLAVOR=J.FLAVOR)
# GROUP BY J.FLAVOR
# ;
SELECT F.FLAVOR
FROM
    (SELECT FLAVOR, SUM(TOTAL_ORDER) FIRST_HALF_TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR) F
    JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) JULY_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) J
    ON F.FLAVOR=J.FLAVOR
ORDER BY F.FIRST_HALF_TOTAL_ORDER+J.JULY_TOTAL_ORDER DESC
LIMIT 3
;

