-- 코드를 입력하세요
SELECT I.ANIMAL_ID ANIMAL_ID, I.NAME NAME
FROM
    (SELECT ANIMAL_ID, NAME, DATETIME
    FROM ANIMAL_INS) I
    JOIN
    (SELECT ANIMAL_ID, NAME, DATETIME
    FROM ANIMAL_OUTS) O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME
;

